package com.example.locationinducedweatherapp.ui.navigation

import com.example.locationinducedweatherapp.util.Constants.Companion.LOCATION_INDUCED_WEATHER_FAILURE_SCREEN
import com.example.locationinducedweatherapp.util.Constants.Companion.LOCATION_INDUCED_WEATHER_REPORT_SCREEN
import com.example.locationinducedweatherapp.util.Constants.Companion.VIEW_FAVOURITE_LOCATION_PROFILES_SCREEN

sealed class LocationInducedWeatherNavigationScreen(val route: String) {
    data object LocationInducedWeatherReportScreen: LocationInducedWeatherNavigationScreen(route = LOCATION_INDUCED_WEATHER_REPORT_SCREEN)
    data object LocationInducedWeatherFailureScreen: LocationInducedWeatherNavigationScreen(route = LOCATION_INDUCED_WEATHER_FAILURE_SCREEN)
    data object ViewFavouriteLocationProfilesScreen: LocationInducedWeatherNavigationScreen(route = VIEW_FAVOURITE_LOCATION_PROFILES_SCREEN)
}